import fs from 'node:fs';
const dir='outputs/mm2-site';
let s=fs.readFileSync('work/reference.html','utf8');
s=s.replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link\b[^>]*>/g,'');
s=s.replace(/<nav class="desktop-nav"[\s\S]*?<\/nav>/,'').replace(/<button class="mobile-menu-button"[\s\S]*?<\/button>/,'');
s=s.replace(/<a href="#" class="brand-sigil"[\s\S]*?<\/a>/,'<a href="#" class="brand-sigil" aria-label="Back to top"><img src="assets/mm2-logo.webp" alt="Murder Mystery 2 logo" width="64" height="64"></a>');
s=s.replace(/<a href="#" class="brand-wordmark">[\s\S]*?<\/a>/,'<a href="#" class="brand-wordmark">MURDER MYSTERY <span>2</span></a>');
s=s.replace(/<video[\s\S]*?<\/video>/,'<img class="hero-video" src="assets/mm2-banner.webp" alt="" fetchpriority="high">').replace(/<button class="video-toggle"[\s\S]*?<\/button>/,'');
s=s.replaceAll('Adopt Me!', 'Murder Mystery 2').replaceAll('Adopt Me','Murder Mystery 2').replaceAll('Uplift Games LLC.','Nikilis').replaceAll('Uplift Games','Nikilis');
s=s.replace(/<footer[\s\S]*?<\/footer>/,'<footer class="site-footer"><p class="copyright">Murder mistery 2 and its artwork belong to Nikilis</p><p class="footer-caption">Korea Server Operation</p><p class="independent-note">Independent website recreation. Not affiliated with Nikilis or Roblox.</p></footer>');
s=s.replace('KOREA SERVER OFFICIALLY HERE!','KOREA SERVER IS HERE!').replace('<span>OFFICIAL</span>','<span>COMMUNITY</span>').replace('Primary Nikilis gateway','Community gateway');
s=s.replace('Perfect for making new friends and roleplaying.','Perfect for making new friends and playing a few rounds.');
s=s.replace(/<button class="pink-button join-button"([^>]*)>JOIN<\/button>/g,'<a class="pink-button join-button"$1 href="https://www.roblox.com/games/142823291/Murder-Mystery-2">JOIN</a>');
s=s.replace(/<button class="pink-button">Join Korean Server<\/button>/,'<a class="pink-button" href="#servers">Join Korean Server</a>').replace(/<button class="secondary-button">Server Guide<\/button>/,'<a class="secondary-button" href="#faq">Server Guide</a>');
const answers=[ 'Use a JOIN button to open Murder Mystery 2 on Roblox. Roblox handles matchmaking; this page does not guarantee a Korean server. For a specific private server, use an invitation from its owner on roblox.com.', 'You can play with friends through Roblox, subject to the game’s server capacity and your account privacy settings.', 'Game events and updates are managed by Nikilis. This independent community page does not control their availability.', 'Open your Roblox account settings and choose Korean under the language setting. In-game translation depends on the game’s supported languages.' ];
let i=0;
s=s.replace(/<div data-state="closed" id="(radix-[^"]+)" hidden="" role="region"([\s\S]*?)><\/div>/g,(_,id,attrs)=>`<div id="${id}" hidden role="region"${attrs}><p class="faq-answer">${answers[i++]}</p></div>`);
s=s.replaceAll('src="/assets/','src="assets/');
s=s.replace('</head>','<link rel="stylesheet" href="reference.css"><link rel="stylesheet" href="style.css"><link rel="icon" href="assets/mm2-logo.webp"></head>').replace('</body>','<script src="app.js"></script></body>');
fs.writeFileSync(dir+'/dist/index.html',s);
fs.writeFileSync(dir+'/.openai/hosting.json',JSON.stringify({static:{directory:'dist'}},null,2));
